### PR TITLE
Refactored billing form

### PR DESCRIPTION
**Pull request by mrbrianevans**
#595 #631

### CODE REVIEW

**Comment by mrbrianevans** [comment]
Ah, good spot! Will sort that out

**Review by w3bdesign — APPROVED** [review]
@mrbrianevans 

Just a minor issue, but I will merge and accept the PR since it seemed to work and the code looked okay. 

Is there any reason why the component doesn't have a return () ?

**Comment by mrbrianevans** [comment]
I'm not sure what you mean by "doesn't have a return ()". Are you refering to the `InputField` component? It is an arrow function with no logic other than what it returns, so there is no function body block.

Its like for example
```typescript
const add = (a,b) => a + b
```
doesn't have an explicit return statement, because there is no logic other than what is returned.

These are equivalent:
```tsx
const InputField = () => <div></div>
```
```tsx
const InputField = () => {
    return <div></div>
}
```

Thanks for merging anyway

**Comment by w3bdesign** [comment]
Yeah, not a big deal, was just wondering.

I have created the Prettier issue and added the hacktoberfest label, so you can get extra credit for the Hacktoberfest.
@mrbrianevans

**Pull request merged**
