### PR TITLE
Add prettier config for formatting

### PR DESCRIPTION
**Pull request by mrbrianevans**
- added config for prettier
- added `package.json` script to format
- run `npm run format`

### CODE REVIEW

**Comment by mrbrianevans** [comment]
Hi Daniel, 
I've added the config and run prettier on the whole project. 

If you would like me to change this pull request to a different branch, then let me know and I can change it without creating a new one.

Brian

**Comment by mrbrianevans** [comment]
This closes #670

**Comment by w3bdesign** [comment]
Looks good, I'll merge and add the hacktoberfest-accepted label.

**Comment by w3bdesign** [comment]
@mrbrianevans 

Thanks for the contribution. 

Do you need to do any additional contributions for Hacktoberfest? 
If yes, I can see if I can find something simple you can do and get it merged ASAP for the deadline.

**Comment by mrbrianevans** [comment]
@w3bdesign yes I still need 2 pull requests to be eligible for hacktoberfest. I've got time today so if there is any react refactoring you need or anything else, please let me know.

**Comment by w3bdesign** [comment]
@mrbrianevans 

Have tagged you in two issues which should be fairly straightforward to fix:

https://github.com/w3bdesign/stein-saks-papir/issues/310

https://github.com/w3bdesign/stein-saks-papir/issues/309

**Comment by mrbrianevans** [comment]
Thanks, will do tonight @w3bdesign

**Pull request merged**
